apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    strimzi.io/node-pools: enabled
    strimizi.io/kraft: "true"
spec:
  kafka:
    version: 4.1.1
    replicas: 3
#    metadataMode: kraft
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
      - name: tls
        port: 9093
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.9"
      defalut.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
    