apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: shared-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster # Kafkaリソースの名前と一致させる
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 5Gi
    class: standard
    deleteClaim: false

